// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TarefaCRUD.Models;

#nullable disable

namespace TarefaCRUD.Migrations
{
    [DbContext(typeof(TarefaDBContext))]
    [Migration("20250416173541_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TarefaCRUD.Models.Pessoa", b =>
                {
                    b.Property<int>("IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPessoa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPessoa"), 1L, 1);

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("NomePessoa")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nomePessoa");

                    b.HasKey("IdPessoa")
                        .HasName("PK__Pessoa__83D303D0AD20D152");

                    b.ToTable("Pessoa", (string)null);
                });

            modelBuilder.Entity("TarefaCRUD.Models.Tarefa", b =>
                {
                    b.Property<int>("IdTarefa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTarefa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTarefa"), 1L, 1);

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("dataInicio");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descricao");

                    b.Property<int?>("IdPessoa")
                        .HasColumnType("int")
                        .HasColumnName("idPessoa");

                    b.Property<DateTime?>("Prazo")
                        .HasColumnType("datetime")
                        .HasColumnName("prazo");

                    b.HasKey("IdTarefa")
                        .HasName("PK__Tarefa__682C5D37667C7B38");

                    b.HasIndex("IdPessoa");

                    b.ToTable("Tarefa", (string)null);
                });

            modelBuilder.Entity("TarefaCRUD.Models.Tarefa", b =>
                {
                    b.HasOne("TarefaCRUD.Models.Pessoa", "IdPessoaNavigation")
                        .WithMany("Tarefas")
                        .HasForeignKey("IdPessoa")
                        .HasConstraintName("FK__Tarefa__idPessoa__38996AB5");

                    b.Navigation("IdPessoaNavigation");
                });

            modelBuilder.Entity("TarefaCRUD.Models.Pessoa", b =>
                {
                    b.Navigation("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
