// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TarefaCRUD.Models;

#nullable disable

namespace TarefaCRUD.Migrations
{
    [DbContext(typeof(TarefaDBContext))]
    [Migration("20250417123644_ConsertarErrosNoContexto")]
    partial class ConsertarErrosNoContexto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TarefaCRUD.Models.Pessoa", b =>
                {
                    b.Property<int>("IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPessoa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPessoa"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("NomePessoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nomePessoa");

                    b.HasKey("IdPessoa");

                    b.ToTable("Pessoa", (string)null);
                });

            modelBuilder.Entity("TarefaCRUD.Models.Tarefa", b =>
                {
                    b.Property<int>("IdTarefa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTarefa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTarefa"), 1L, 1);

                    b.Property<DateTime?>("DataInicio")
                        .IsRequired()
                        .HasColumnType("date")
                        .HasColumnName("dataInicio");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("descricao");

                    b.Property<int?>("IdPessoa")
                        .HasColumnType("int")
                        .HasColumnName("idPessoa");

                    b.Property<DateTime?>("Prazo")
                        .IsRequired()
                        .HasColumnType("date")
                        .HasColumnName("prazo");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("prioridade");

                    b.HasKey("IdTarefa");

                    b.HasIndex("IdPessoa");

                    b.ToTable("Tarefa", (string)null);
                });

            modelBuilder.Entity("TarefaCRUD.Models.Tarefa", b =>
                {
                    b.HasOne("TarefaCRUD.Models.Pessoa", "IdPessoaNavigation")
                        .WithMany("Tarefas")
                        .HasForeignKey("IdPessoa")
                        .HasConstraintName("FK_Tarefa_Pessoa");

                    b.Navigation("IdPessoaNavigation");
                });

            modelBuilder.Entity("TarefaCRUD.Models.Pessoa", b =>
                {
                    b.Navigation("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
